//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FerreteriaYerias
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPROBANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPROBANTE()
        {
            this.DETALLE_COMPROBANTE = new HashSet<DETALLE_COMPROBANTE>();
        }
    
        public int NumComprobante { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NomUsuario { get; set; }
        public string NomCliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string TipoComprobante { get; set; }
        public Nullable<decimal> IGVComprobante { get; set; }
        public Nullable<System.DateTime> FechaComprobante { get; set; }
        public string ApeCliente { get; set; }
        public Nullable<int> IdPago { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPROBANTE> DETALLE_COMPROBANTE { get; set; }
        public virtual PAGO PAGO { get; set; }
    }
}
